Repository jacobras/Human-Readable, pull requests merged in 2024-08, with the labels that each got.

#53 feat: add portuguese
  src/appleAndJsMain/kotlin/nl/jacobras/humanreadable/extendLibresPlurals.kt
  src/commonMain/libres/strings/time_units_pt.xml
  src/commonTest/kotlin/nl/jacobras/humanreadable/localized/LocalizedTests.kt
Labels: localization

#84 Fix 364 days edge case
  src/commonMain/kotlin/nl/jacobras/humanreadable/HumanReadableDuration.kt
  src/commonTest/kotlin/nl/jacobras/humanreadable/HumanReadableDurationTests.kt
Labels: bug

#85 Update Kotlin/Compose/DateTime
  .gitignore
  build.gradle.kts
  demo/README.md
  demo/build.gradle.kts
  docs/composeApp.js
  docs/composeApp.js.map
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew.bat
Labels: dependencies

#83 Support different cases for past/future times
  .github/workflows/build.yml
  src/commonMain/kotlin/nl/jacobras/humanreadable/HumanReadable.kt
  src/commonMain/kotlin/nl/jacobras/humanreadable/HumanReadableDuration.kt
  src/commonMain/kotlin/nl/jacobras/humanreadable/HumanReadableRelativeTime.kt
  src/commonMain/kotlin/nl/jacobras/humanreadable/RelativeTime.kt
  src/commonMain/kotlin/nl/jacobras/humanreadable/SafelyTranslate.kt
  src/commonMain/kotlin/nl/jacobras/humanreadable/TimeUnit.kt
  src/commonMain/libres/strings/time_units_de.xml
  src/commonMain/libres/strings/time_units_en.xml
  src/commonMain/libres/strings/time_units_pl.xml
  src/commonMain/libres/strings/time_units_ru.xml
  src/commonTest/kotlin/nl/jacobras/humanreadable/localized/LocalizedTests.kt
Labels: bug
